# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

In [2]:
x = np.random.random((3,3,3))
print(x)

[[[0.95000408 0.68588965 0.17182191]
  [0.07418917 0.65873783 0.51954407]
  [0.88699821 0.33142549 0.67885702]]

 [[0.7984258  0.50431965 0.67459823]
  [0.93713677 0.42209372 0.52937523]
  [0.44758443 0.77900301 0.92222508]]

 [[0.36146871 0.79353089 0.4915737 ]
  [0.94862363 0.42158725 0.8625617 ]
  [0.92745662 0.46210132 0.52681862]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
y = np.diag([1, 2, 3, 4, 5])
print(y)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
a = np.ones((3,3))
print("Checkerboard pattern:")
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.61182215 0.42745551 0.72499031 0.88859426 0.47331614]
 [0.87195779 0.58139036 0.64288857 0.11123601 0.67000332]
 [0.01411107 0.14826535 0.88944626 0.06062113 0.13532485]
 [0.30587967 0.09432282 0.82470005 0.70617026 0.78486701]
 [0.60175229 0.74703409 0.54721926 0.49784883 0.41035221]]
After normalization:
[[0.6828368  0.47221275 0.81212232 0.99902666 0.52460483]
 [0.98002083 0.64807092 0.71832768 0.11095742 0.7493041 ]
 [0.         0.15326047 1.         0.053134   0.13847698]
 [0.33332214 0.09163547 0.92603266 0.79062192 0.88052662]
 [0.67133279 0.83730555 0.6090332  0.55263145 0.45267361]]


# 5.  How to find common values between two arrays?

In [6]:
arr1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",arr1)
arr2 = [10, 30, 40]
print("Array2: ",arr2)
print("Common values between two arrays:")
print(np.intersect1d(arr1, arr2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [8]:
A = np.random.randint(0,2,6)
print("First array:")
print(A)
B = np.random.randint(0,2,6)
print("Second array:")
print(B)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(A, B)
print(array_equal)

First array:
[1 1 1 1 0 1]
Second array:
[0 0 0 0 0 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.53081374 0.0094938  0.53257225 0.79667649 0.12084466 0.15496691
 0.72326341 0.2572018  0.09718665 0.54252709]
Maximum value replaced by 0:
[0.53081374 0.0094938  0.53257225 0.         0.12084466 0.15496691
 0.72326341 0.2572018  0.09718665 0.54252709]


# 9. How to print all the values of an array?

In [15]:
import sys
np.set_printoptions(threshold=sys.maxsize)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [16]:
print("Original matrix:\n")
P = np.random.rand(5, 10)
print(P)
print("\nSubtract the mean of each row of the said matrix:\n")
Q = P - P.mean(axis=1, keepdims=True)
print(Q)

Original matrix:

[[0.17180549 0.22772725 0.59403263 0.58717406 0.97480955 0.20010558
  0.71209472 0.72205134 0.74323423 0.00293406]
 [0.68622964 0.75688709 0.09181012 0.13634882 0.39860525 0.86548141
  0.04984422 0.12557706 0.56952521 0.45500687]
 [0.73173664 0.70984686 0.01798003 0.07622036 0.67593183 0.93030244
  0.09646245 0.66411447 0.55930785 0.68523792]
 [0.57238749 0.26808676 0.21305473 0.92904355 0.71270882 0.25247538
  0.34772726 0.91314079 0.67459631 0.81732949]
 [0.0325409  0.57259844 0.00265003 0.07183202 0.91121085 0.80186816
  0.15463699 0.36198496 0.40734506 0.18867026]]

Subtract the mean of each row of the said matrix:

[[-0.3217914  -0.26586964  0.10043574  0.09357717  0.48121266 -0.29349131
   0.21849783  0.22845444  0.24963733 -0.49066283]
 [ 0.27269807  0.34335552 -0.32172145 -0.27718275 -0.01492632  0.45194984
  -0.36368735 -0.28795451  0.15599364  0.0414753 ]
 [ 0.21702256  0.19513278 -0.49673405 -0.43849372  0.16121775  0.41558835
  -0.41825164  0.14940038  0.0

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [17]:
vector = np.array([1, 2, 3, 4, 5, 6])

In [18]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [19]:
vector[2]

3

In [22]:
matrix[:,1]

array([2, 5, 8])

In [25]:
matrix[:,1+1]

array([3, 6, 9])

# 12.How to get the diagonal of a dot product?

In [26]:
a = np.arange(25).reshape(5,5)
np.einsum('ii->i', a)

array([ 0,  6, 12, 18, 24])

In [27]:
np.einsum(a, [0,0], [0])
np.diag(a)

array([ 0,  6, 12, 18, 24])

# 13.How to find the most frequent value in an array?

In [28]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[6 8 9 1 9 4 8 6 4 4 1 4 2 7 6 0 1 1 0 6 4 6 4 0 6 2 2 3 7 8 7 5 3 2 6 2 2
 1 4 6]
Most frequent value in the above array:
6


# 14.How to get the n largest values of an array

In [29]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [30]:
arra1 = np.array([("Diana Penty", 88.5, 90),
                 ("Fredick vantur", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Diana Penty' '88.5' '90']
 ['Fredick vantur' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Diana Penty', 88.5, 90) (b'Fredick vantur', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
